apiVersion: v1
kind: Pod
metadata:
  name: myapp
  labels:
    app: myapp
spec:
  serviceAccountName: litmus-runner 
  containers:
  - name: myapp
    image: litmuschaos/go-runner:ci
    command: ['sh', '-c', "while true; do echo && kubectl get pods -n litmus && sleep 2; done;"]
