apiVersion: litmuschaos.io/v1alpha1
kind: ChaosEngine
metadata:
  name: helloservice-pod-delete
spec:
  engineState: "active"
  annotationCheck: "false"
  components:
    runner:
      image: "litmuschaos/chaos-runner:ci"
      imagePullPolicy: "Always"
  appinfo:
    appns: "monitoring"
    applabel: "app=helloservice"
    appkind: "deployment"
  jobCleanUpPolicy: 'retain'
  chaosServiceAccount: litmus
  monitoring: true
  experiments:
  - name: pod-delete
    spec:
      probe:
      - name: helloservice-k8s-probe
        type: "k8sProbe"
        k8sProbe/inputs:
          command:
            group: ""
            version: "v1"
            resource: "pods"
            namespace: "monitoring"
            labelSelector: "app=helloservice"
        operation: "present"
        mode: "Edge"
        runProperties:
          probeTimeout: 10
          interval: 5
          retry: 1
          probePollingInterval: 2
