apiVersion: litmuschaos.io/v1alpha1
kind: ChaosEngine
metadata:
  name: helloservice-pod-delete
spec:
  engineState: "active"
  annotationCheck: "false"
  components:
    runner:
      image: "litmuschaos/chaos-runner:latest"
      imagePullPolicy: "Always"
  appinfo:
    appns: "monitoring"
    applabel: "app=helloservice"
    appkind: "deployment"
  jobCleanUpPolicy: 'retain'
  chaosServiceAccount: litmus
  experiments:
  - name: pod-delete
    spec:
      probe:
      - name: helloservice-prom-probe
        type: "PromProbe"
        promProbe/inputs:
          endpoint: "http://34.123.7.221:31090"
          query: "avg_over_time(probe_duration_seconds{instance='helloservice.monitoring.svc.cluster.local:80',job='blackbox'}[10s])*1000"
          comparator:
            criteria: "<="
            value: "30" # in ms
        mode: "Continuous" 
        runProperties:
          probeTimeout: 10
          interval: 5
          retry: 1
          probePollingInterval: 2
      - name: helloservice-cmd-probe
        type: "cmdProbe"
        cmdProbe/inputs:
          command: "curl -o /dev/null -s -w '%{http_code}' http://34.70.7.60"
          source: "inline"
          comparator:
            type: "int"
            criteria: "=="
            value: "200"
        mode: "Continuous"
        runProperties:
          probeTimeout: 10
          interval: 5
          retry: 1
          probePollingInterval: 2
      - name: helloservice-http-probe
        type: "httpProbe"
        httpProbe/inputs:
          url: "http://34.70.7.60:80"
          insecureSkipVerify: false
          method:
            get: 
              criteria: "==" # supports == & != and oneof operations
              responseCode: "200"
        mode: "Continuous" 
        runProperties:
          probeTimeout: 10
          interval: 5
          retry: 1
          probePollingInterval: 2
      - name: helloservice-prom-probe
        type: "PromProbe"
        promProbe/inputs:
          endpoint: "http://34.123.7.221:31090"
          query: "avg_over_time(probe_duration_seconds{instance='helloservice.monitoring.svc.cluster.local:80',job='blackbox'}[10s])*1000"
          comparator:
            criteria: "<="
            value: "30" # in ms
        mode: "Continuous" 
        runProperties:
          probeTimeout: 10
          interval: 5
          retry: 1
          probePollingInterval: 2

