apiVersion: litmuschaos.io/v1alpha1
kind: ChaosEngine
metadata:
  name: helloservice-pod-delete
spec:
  engineState: "active"
  annotationCheck: "false"
  components:
    runner:
      image: "litmuschaos/chaos-runner:latest"
      imagePullPolicy: "Always"
  appinfo:
    appns: "monitoring"
    applabel: "app=helloservice"
    appkind: "deployment"
  jobCleanUpPolicy: 'retain'
  chaosServiceAccount: litmus
  experiments:
  - name: pod-delete
    spec:
      probe:
      - name: helloservice-http-probe
        type: "httpProbe"
        httpProbe/inputs:
          url: "http://34.70.7.60:80"
          insecureSkipVerify: false
          method:
            get: 
              criteria: "==" # supports == & != and oneof operations
              responseCode: "200"
        mode: "Continuous" 
        runProperties:
          probeTimeout: 10
          interval: 5
          retry: 1
          probePollingInterval: 2
