apiVersion: v1
kind: ServiceAccount
metadata:
  name: litmus-runner
  namespace: default
  labels:
    name: litmus-runner
---
# Source: openebs/templates/clusterrole.yaml
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: litmus-runner
  labels:
    name: litmus-runner
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: litmus-runner
  labels:
    name: litmus-runner
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: litmus-runner
subjects:
- kind: ServiceAccount
  name: litmus-runner
  namespace: default
