name: Litmus-CI
on:
  issue_comment:
    types: [created]
    branches:
      - master

jobs:
     
  merge:  
    if: contains(github.event.comment.html_url, '/pull/') && startsWith(github.event.comment.body, '/merge')
    runs-on: ubuntu-latest
    steps:
      - name: Add a merge label when all jobs are passed
        uses: actions-ecosystem/action-add-labels@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          labels: merge

      - name: automerge
        uses: davideviolante/pr-automerge-action@v1.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          merge-method: 'squash' # Default 'squash'
          min-approvals: 0 # Default 2
          base-ref: 'master'         
            
#         uses: "pascalgn/automerge-action@f81beb99aef41bb55ad072857d43073fba833a98"
#         env:          
#           GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
#           MERGE_LABELS: "merge,!WIP"
#           MERGE_METHOD: "squash"
#           MERGE_FORKS: "false"
#           MERGE_RETRIES: "6"
#           MERGE_RETRY_SLEEP: "10000"
#           UPDATE_LABELS: ""
#           UPDATE_METHOD: "rebase" 
          
          
# name: AutoRelease

# on:
#   push:
#     branches: [ master ]
#   pull_request:
#     branches: [ master ]

# jobs:
#   release:
#     name: "Release"
#     runs-on: "ubuntu-latest"

#     steps:
#       # ...
#       - name: "Build & test"
#         run: |
#           echo "done!"
          
#       - uses: peterjgrainger/action-create-branch@v1.0.0
#         env:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#         with:
#           branch: '${{ secrets.RELEASE_BRANCH }}'
            
#       - uses: "marvinpinto/action-automatic-releases@latest"
#         with:
#           repo_token: "${{ secrets.GITHUB_TOKEN }}"
#           automatic_release_tag: "${{ secrets.RELEASE_TAG }}"
#           prerelease: false
#           title: "${{ secrets.RELEASE_TAG }}"
#           files: |
#             LICENSE.txt
#             *.jar
