---
name: AutoRelease

# Executes a job at 10:15am on the 15th day of every month
on:
  schedule:
    - cron:  '0 15 10 15 * *'

jobs:
  release:
    name: "Release"
    runs-on: "ubuntu-latest"

    steps:
      - name: "Build & test"
        run: |
          docker build -f build/ansible-runner/Dockerfile litmuschaos/ansible-runner:ci .

      # Provide release tag from the github secret
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "${{ secrets.RELEASE_TAG }}"
          prerelease: false
          title: "${{ secrets.RELEASE_TAG }}"






# name: AutoRelease

# on:
#   push:
#     branches: [ master ]
#   pull_request:
#     branches: [ master ]

# jobs:
#   release:
#     name: "Release"
#     runs-on: "ubuntu-latest"

#     steps:
      
#       - uses: "marvinpinto/action-automatic-releases@latest"
#         with:
#           repo_token: "${{ secrets.GITHUB_TOKEN }}"
#           automatic_release_tag: "${{ secrets.RELEASE_TAG }}"
#           prerelease: false
#           title: "${{ secrets.RELEASE_TAG }}"
