name: AutoRelease

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  release:
    name: "Release"
    runs-on: "ubuntu-latest"

    steps:
      # ...
      - name: "Build & test"
        run: |
          echo "done!"

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "${{ secrets.RELEASE_TAG }}"
          prerelease: false
          title: "${{ secrets.RELEASE_TAG }}"
          files: |
            LICENSE.txt
            *.jar
